[package]
name = "led-rtic"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-rtic = "0.5.6"
microbit = "0.9.0"
panic-semihosting = "0.5.6"
