[package]
name = "led-rtic"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-rtic = "1.1.3"
microbit = "0.13.0"
panic-halt = "0.2.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
