[package]
name = "microrust-start"
version = "0.1.0"
authors = ["Armin Häberling <armin.aha@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-rt = "0.7.1"
microbit = "0.13.0"
panic-semihosting = "0.6.0"
